n1 = int(input('Qual numero quer saber a Tabuada? '))

x0 = n1 * 0
x1 = n1 * 1
x2 = n1 * 2
x3 = n1 * 3
x4 = n1 * 4
x5 = n1 * 5
x6 = n1 * 6
x7 = n1 * 7
x8 = n1 * 8
x9 = n1 * 9 
x10 = n1 * 10
print('Aqui esta a tabuada do numero {}'.format(n1))

print('{}*0 = {}'.format(n1,x0)) 
print('{}*1 = {}'.format(n1,x1))
print('{}*2 = {}'.format(n1,x2))
print('{}*3 = {}'.format(n1,x3))
print('{}*4 = {}'.format(n1,x4))
print('{}*5 = {}'.format(n1,x5))
print('{}*6 = {}'.format(n1,x6))
print('{}*7 = {}'.format(n1,x7))
print('{}*8 = {}'.format(n1,x8))
print('{}*9 = {}'.format(n1,x9))
print('{}*10 = {}'.format(n1,x10))
print('Obrigado por usar Meu sistema !!')

# esse eu tive que quebrar um pouqinho a cabeça, precisei recorrer a pesquisas pra me basear, sei que tem formas mais faceis e simples de fazer
# mas quis fazer do meu jeito, sem copiar ninguem, apenas o conhecimento que ja tenho e minha pouca criatividade. 
